### ISSUE TITLE
PHP 8.4 deprecations require reactphp/promise breaking changes

### ISSUE THREAD

**Issue by glo71317** [reactphp/promise#265] opened 2024-12-14 07:43 UTC
**Addressing PHP 8.4 Deprecations:**

With the release of PHP 8.4, several deprecations and breaking changes have been introduced that may require attention in order to ensure continued compatibility and avoid potential issues. We are keen to address these changes and adapt our codebase to fully support PHP 8.4 without introducing any breaking changes for our users.

**Some of the key deprecations to be aware of include:**

1. Implicitly marking parameter $onRejected as nullable is deprecated: The explicit nullable type must be used instead.
2. Deprecation of the E_STRICT constant: This constant is no longer supported in PHP 8.4.
3. session_set_save_handler() with more than two arguments: This usage is now deprecated in PHP 8.4.

We would like to inquire if there is a plan to address these deprecations in the near future and would be more than happy to contribute to this effort. By collaborating, we can help ensure that the transition to PHP 8.4 is as smooth as possible for all users and avoid any disruptions caused by these changes.

Please let us know how we can assist in this process, and if there are any specific steps we should follow to contribute towards the resolution of these issues.

Looking forward to your response.

```php
Deprecated: React\Promise\Internal\FulfilledPromise::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php on line 37
Deprecated: React\Promise\Internal\FulfilledPromise::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php on PHP Deprecated:  React\Promise\Promise::__construct(): Implicitly marking parameter $canceller as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 32
PHP Deprecated:  React\Promise\Promise::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 44
PHP Deprecated:  React\Promise\Promise::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 44
Deprecated: React\Promise\Promise::__construct(): Implicitly marking parameter $canceller as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 32
Deprecated: React\Promise\Promise::then(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 44
Deprecated: React\Promise\Promise::then(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 44
Deprecated: React\Promise\Promise::resolver(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 169
Deprecated: React\Promise\Promise::resolver(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 169
PHP Deprecated:  React\Promise\Promise::resolver(): Implicitly marking parameter $onFulfilled as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 169
PHP Deprecated:  React\Promise\Promise::resolver(): Implicitly marking parameter $onRejected as nullable is deprecated, the explicit nullable type must be used instead in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php on line 169
```

**Comment by clue** [comment] 2024-12-14 10:49
We have you covered already from day one, it looks like you're using an outdated version, please update to the latest version first.

Closing as duplicate of https://github.com/orgs/reactphp/discussions/589 and https://github.com/reactphp/promise/pull/260.

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/reactphp) ❤️

**Closed as not planned by clue** 2024-12-14 10:49 UTC
Labels: invalid
