### ISSUE TITLE
Problem with PHP 8

### ISSUE THREAD

**Issue by my-random-username** [reactphp/promise#192] opened 2021-07-24 14:28 UTC
The "otherwise" method on Promise seems to have a problem with PHP8
it will throw this exception : 

#message: "Method ReflectionParameter::getClass() is deprecated"
  #code: 0
  #file: "./vendor/react/promise/src/functions.php"
  #line: 346
  #severity: E_DEPRECATED

it seems the problem is caused by :
\React\Promise\Promise - Line : 77
\React\Promise - functions.php - Line : 346

https://github.com/reactphp/promise/blob/a9752a861e21c0fe0b380c9f9e55beddc0ed7d31/src/functions.php#L346

**update:**

This method is deprecated in the current version of PHP (8) :
[Reference](https://www.php.net/manual/en/reflectionparameter.getclass.php)

This notice can be turned off using native php **error_reporting()** function.
[Reference](https://www.php.net/manual/en/function.error-reporting.php)

run time error reporting setting :
error_reporting(error_reporting() & ~E_DEPRECATED);

**Comment by clue** [comment] 2021-11-17 15:44
@my-random-username Thank you for reporting!

This has been addressed with #198 that will be released as part of the `v2.9.0` release.

Duplicate of #181

**Closed by clue** 2021-11-17 15:44 UTC
Labels: bug, new feature

**Comment by SimonFrings** [comment] 2022-02-10 12:12
Hey @SwenVanZanten, this won't take long, our plan is to get this out in the next few days :rocket:
