### ISSUE TITLE
Getting undefined function

### ISSUE THREAD

**Issue by domagala** [reactphp/promise#27] opened 2015-03-09 12:49 UTC
Hi,

When using composer to install your lib I get the following error when consuming it.
Call to undefined function React\Promise\resolve()

Any idea what could be causing this?

**Comment by jsor** [comment] 2015-03-09 15:25
Could you provide a little bit more context? Maybe the full stacktrace or at least the file and line where the error happens. And ideally a reproducible test case with composer.json etc.

**Comment by jsor** [comment] 2015-04-10 07:30
I'm closing this for now, feel free to reopen if you still have questions.

**Closed by jsor** 2015-04-10 07:30 UTC

**Comment by domagala** [comment] 2015-04-10 08:41
Thanks

**Comment by ankitapage** [comment] 2015-05-29 09:27
Hi,
I got the same error "Call to undefined function React\Promise\resolve()" and its in file "FatalErrorException in Promise.php line 128".
Can you please tell me what is causing this error.

Thanks.

**Comment by domagala** [comment] 2015-05-29 09:57
Hi,

Make sure your composer autoload class is loading this library correctly.

**Comment by jsor** [comment] 2015-05-29 09:59
If you're using a custom autoloader, make sure you include the [functions.php](https://github.com/reactphp/promise/blob/master/src/functions.php).

**Comment by ankitapage** [comment] 2015-05-29 10:24
@domagala Thanks, got its resolved. 
@jsor Thanks to u 2.

**Comment by danielecr** [comment] 2019-07-26 07:39
please: document
HOW do include functions.php, where?
I am using autoload.php generated by composer, is it a "custom" autoloader?

**Comment by WyriHaximus** [comment] 2019-07-26 08:09
@danielecr It's loaded through `functions_include.php` by composer: https://github.com/reactphp/promise/blob/master/composer.json#L18

**Comment by danielecr** [comment] 2019-07-26 08:12
sorry, maybe I need more sleep, but in documentation (README.md) it is written:

> $promise = React\Promise\FulfilledPromise($value);

and I was doing just that, not

> $promise = new React\Promise\FulfilledPromise($value);

or it is due to newer php to be pedant on this? I am not a php lover, I just use it

**Comment by WyriHaximus** [comment] 2019-07-26 09:28
> > $promise = new React\Promise\FulfilledPromise($value);
> 
> or it is due to newer php to be pedant on this? I am not a php lover, I just use it

Well that is indeed the correct way to write it. That's not a function but a class and the missing `new` is an error on our side. Could you open a PR fixing it for that line and for the `RejectedPromise` right below it?

**Comment by danielecr** [comment] 2019-08-02 08:11
@WyriHaximus #145 is still waiting

**Comment by WyriHaximus** [comment] 2019-08-02 09:18
@danielecr Indeed it is
