### ISSUE TITLE
Unhandled promise

### ISSUE THREAD

**Issue by sm2017** [reactphp/promise#106] opened 2017-11-30 09:24 UTC
I think it's good that we have a method like `set_exception_handler` for promise that sets a user-defined unhandled promise rejection handler function

**Comment by kelunik** [comment] 2017-11-30 09:39
While sometimes useful, it could also be unhelpful in other situations. Imagine situations where something is fetched and the promise is resolved with an object, but that object provides access to further promise operations, which are executed eagerly, so there might be no interest in these promises at all, whether they succeed or fail. What's your suggestion to mark these as _"not interested"_?

**Comment by sm2017** [comment] 2017-11-30 13:48
Unhanded promise rejection in asynchronous programing is same as uncaught exception in synchronous programming. Is there any "not interested" for `set_exception_handler`?

`exception_handler` is a function to be called when an uncaught exception occurs. You can have many exception types and in handler function ignore some types (using `instance of` operator)

In JavaScript we have same solution . see https://stackoverflow.com/questions/31472439/catch-all-unhandled-javascript-promise-rejections

**Comment by jsor** [comment] 2017-12-01 07:09
I'm planning of introducing something like this in the future, see also  #87.

**Comment by clue** [comment] 2021-04-05 10:37
Closing as duplicate of #87.

**Closed by clue** 2021-04-05 10:37 UTC
